Arrays.o: Arrays.cpp ./config/config.h Arrays.h GException.h DjVuGlobal.h \
  GSmartPointer.h ByteStream.h
BSByteStream.o: BSByteStream.cpp ./config/config.h BSByteStream.h ByteStream.h \
  Arrays.h GException.h DjVuGlobal.h GSmartPointer.h ZPCodec.h \
  GContainer.h
BSEncodeByteStream.o: BSEncodeByteStream.cpp ./config/config.h BSByteStream.h \
  ByteStream.h Arrays.h GException.h DjVuGlobal.h GSmartPointer.h \
  ZPCodec.h GContainer.h GString.h
ByteStream.o: ByteStream.cpp ./config/config.h DjVuGlobal.h ByteStream.h \
  Arrays.h GException.h GSmartPointer.h GOS.h GString.h GContainer.h \
  GURL.h GThreads.h DjVuMessage.h DjVuMessageLite.h
DataPool.o: DataPool.cpp ./config/config.h DataPool.h GThreads.h DjVuGlobal.h \
  GException.h GString.h GContainer.h GSmartPointer.h GURL.h Arrays.h \
  IFFByteStream.h ByteStream.h GOS.h debug.h
ddjvuapi.o: ddjvuapi.cpp ./config/config.h GException.h DjVuGlobal.h \
  GSmartPointer.h GThreads.h GContainer.h ByteStream.h Arrays.h \
  IFFByteStream.h GString.h BSByteStream.h ZPCodec.h GBitmap.h GPixmap.h \
  GScaler.h GRect.h DjVuPort.h GURL.h DataPool.h DjVuInfo.h IW44Image.h \
  DjVuImage.h DjVuFile.h DjVuPalette.h DjVuAnno.h DjVuFileCache.h \
  DjVuDocument.h DjVuDumpHelper.h DjVuMessageLite.h DjVuMessage.h \
  DjVmNav.h DjVuText.h GMapAreas.h DjVuToPS.h DjVmDir.h DjVmDir0.h \
  DjVuNavDir.h DjVmDoc.h miniexp.h ddjvuapi.h
debug.o: debug.cpp ./config/config.h debug.h
DjVmDir0.o: DjVmDir0.cpp ./config/config.h DjVmDir0.h GString.h DjVuGlobal.h \
  GContainer.h GException.h GSmartPointer.h ByteStream.h Arrays.h debug.h
DjVmDir.o: DjVmDir.cpp ./config/config.h DjVmDir.h GString.h DjVuGlobal.h \
  GContainer.h GException.h GSmartPointer.h GThreads.h BSByteStream.h \
  ByteStream.h Arrays.h ZPCodec.h GURL.h debug.h
DjVmDoc.o: DjVmDoc.cpp ./config/config.h DjVmDoc.h DjVmDir.h GString.h \
  DjVuGlobal.h GContainer.h GException.h GSmartPointer.h GThreads.h \
  DjVmNav.h DataPool.h GURL.h Arrays.h IFFByteStream.h ByteStream.h GOS.h \
  debug.h
DjVmNav.o: DjVmNav.cpp ./config/config.h DjVuDocument.h DjVuPort.h GThreads.h \
  DjVuGlobal.h GException.h GURL.h GString.h GContainer.h GSmartPointer.h \
  Arrays.h DjVmNav.h BSByteStream.h ByteStream.h ZPCodec.h debug.h
DjVuAnno.o: DjVuAnno.cpp ./config/config.h DjVuAnno.h GString.h DjVuGlobal.h \
  GContainer.h GException.h GSmartPointer.h IFFByteStream.h ByteStream.h \
  Arrays.h BSByteStream.h ZPCodec.h GMapAreas.h GRect.h GURL.h GThreads.h \
  debug.h
DjVuDocEditor.o: DjVuDocEditor.cpp ./config/config.h DjVuDocEditor.h \
  DjVuDocument.h DjVuPort.h GThreads.h DjVuGlobal.h GException.h GURL.h \
  GString.h GContainer.h GSmartPointer.h Arrays.h DjVmDoc.h DjVmDir.h \
  DjVuImage.h DjVuFile.h DjVuInfo.h GRect.h DjVuPalette.h GPixmap.h \
  DjVuAnno.h IFFByteStream.h ByteStream.h DataPool.h IW44Image.h \
  ZPCodec.h GOS.h DjVmNav.h debug.h
DjVuDocument.o: DjVuDocument.cpp ./config/config.h DjVuDocument.h DjVuPort.h \
  GThreads.h DjVuGlobal.h GException.h GURL.h GString.h GContainer.h \
  GSmartPointer.h Arrays.h DjVmDoc.h DjVmDir.h DjVmDir0.h DjVmNav.h \
  DjVuNavDir.h DjVuImage.h DjVuFile.h DjVuInfo.h GRect.h DjVuPalette.h \
  GPixmap.h DjVuAnno.h DjVuFileCache.h IFFByteStream.h ByteStream.h GOS.h \
  DataPool.h IW44Image.h ZPCodec.h debug.h
DjVuDumpHelper.o: DjVuDumpHelper.cpp ./config/config.h DjVuDumpHelper.h \
  GSmartPointer.h DjVuGlobal.h DataPool.h GThreads.h GException.h \
  GString.h GContainer.h GURL.h Arrays.h DjVmDir.h DjVuInfo.h GRect.h \
  IFFByteStream.h ByteStream.h
DjVuErrorList.o: DjVuErrorList.cpp ./config/config.h DjVuErrorList.h DjVuPort.h \
  GThreads.h DjVuGlobal.h GException.h GURL.h GString.h GContainer.h \
  GSmartPointer.h Arrays.h DjVmDoc.h DjVmDir.h GOS.h DataPool.h
DjVuFileCache.o: DjVuFileCache.cpp ./config/config.h DjVuFileCache.h DjVuFile.h \
  DjVuInfo.h GSmartPointer.h DjVuGlobal.h GRect.h DjVuPalette.h \
  GContainer.h GException.h GPixmap.h DjVuPort.h GThreads.h GURL.h \
  GString.h Arrays.h debug.h
DjVuFile.o: DjVuFile.cpp ./config/config.h DjVuFile.h DjVuInfo.h \
  GSmartPointer.h DjVuGlobal.h GRect.h DjVuPalette.h GContainer.h \
  GException.h GPixmap.h DjVuPort.h GThreads.h GURL.h GString.h Arrays.h \
  IFFByteStream.h ByteStream.h GOS.h MMRDecoder.h JPEGDecoder.h \
  DjVuAnno.h DjVuText.h GMapAreas.h DataPool.h JB2Image.h ZPCodec.h \
  IW44Image.h DjVuNavDir.h BSByteStream.h debug.h
DjVuGlobal.o: DjVuGlobal.cpp ./config/config.h
DjVuGlobalMemory.o: DjVuGlobalMemory.cpp ./config/config.h
DjVuImage.o: DjVuImage.cpp ./config/config.h DjVuImage.h DjVuFile.h DjVuInfo.h \
  GSmartPointer.h DjVuGlobal.h GRect.h DjVuPalette.h GContainer.h \
  GException.h GPixmap.h DjVuPort.h GThreads.h GURL.h GString.h Arrays.h \
  DjVuAnno.h GScaler.h GBitmap.h DjVuDocument.h JB2Image.h ZPCodec.h \
  IW44Image.h DataPool.h ByteStream.h GMapAreas.h DjVuText.h \
  IFFByteStream.h BSByteStream.h debug.h
DjVuInfo.o: DjVuInfo.cpp ./config/config.h DjVuInfo.h GSmartPointer.h \
  DjVuGlobal.h GRect.h GException.h ByteStream.h Arrays.h GString.h \
  GContainer.h
DjVuMessage.o: DjVuMessage.cpp ./config/config.h DjVuMessage.h \
  DjVuMessageLite.h GString.h DjVuGlobal.h GContainer.h GException.h \
  GSmartPointer.h GOS.h XMLTags.h ByteStream.h Arrays.h GURL.h GThreads.h \
  debug.h
DjVuMessageLite.o: DjVuMessageLite.cpp ./config/config.h DjVuMessageLite.h \
  GString.h DjVuGlobal.h GContainer.h GException.h GSmartPointer.h GOS.h \
  XMLTags.h ByteStream.h Arrays.h GURL.h GThreads.h debug.h
DjVuNavDir.o: DjVuNavDir.cpp ./config/config.h DjVuNavDir.h GString.h \
  DjVuGlobal.h GContainer.h GException.h GSmartPointer.h GThreads.h \
  GURL.h Arrays.h debug.h GOS.h ByteStream.h
DjVuPalette.o: DjVuPalette.cpp ./config/config.h GException.h DjVuGlobal.h \
  ByteStream.h Arrays.h GSmartPointer.h BSByteStream.h ZPCodec.h \
  GContainer.h DjVuPalette.h GPixmap.h
DjVuPort.o: DjVuPort.cpp ./config/config.h DjVuPort.h GThreads.h DjVuGlobal.h \
  GException.h GURL.h GString.h GContainer.h GSmartPointer.h Arrays.h \
  GOS.h DjVuImage.h DjVuFile.h DjVuInfo.h GRect.h DjVuPalette.h GPixmap.h \
  DjVuAnno.h DjVuDocument.h DjVuMessageLite.h DataPool.h
DjVuText.o: DjVuText.cpp ./config/config.h DjVuText.h GMapAreas.h \
  GSmartPointer.h DjVuGlobal.h GContainer.h GException.h GString.h \
  GRect.h GURL.h Arrays.h GThreads.h IFFByteStream.h ByteStream.h \
  BSByteStream.h ZPCodec.h debug.h
DjVuToPS.o: DjVuToPS.cpp ./config/config.h DjVuToPS.h DjVuGlobal.h GRect.h \
  DjVuDocument.h DjVuPort.h GThreads.h GException.h GURL.h GString.h \
  GContainer.h GSmartPointer.h Arrays.h DjVuText.h GMapAreas.h \
  IFFByteStream.h ByteStream.h BSByteStream.h ZPCodec.h DjVuImage.h \
  DjVuFile.h DjVuInfo.h DjVuPalette.h GPixmap.h DjVuAnno.h DataPool.h \
  IW44Image.h JB2Image.h GBitmap.h debug.h
GBitmap.o: GBitmap.cpp ./config/config.h GBitmap.h GSmartPointer.h DjVuGlobal.h \
  ByteStream.h Arrays.h GException.h GRect.h GString.h GContainer.h \
  GThreads.h
GContainer.o: GContainer.cpp ./config/config.h GContainer.h GException.h \
  DjVuGlobal.h GSmartPointer.h
GException.o: GException.cpp ./config/config.h GException.h DjVuGlobal.h \
  DjVuMessageLite.h GString.h GContainer.h GSmartPointer.h debug.h
GIFFManager.o: GIFFManager.cpp ./config/config.h GIFFManager.h IFFByteStream.h \
  DjVuGlobal.h GException.h GString.h GContainer.h GSmartPointer.h \
  ByteStream.h Arrays.h debug.h
GMapAreas.o: GMapAreas.cpp ./config/config.h GMapAreas.h GSmartPointer.h \
  DjVuGlobal.h GContainer.h GException.h GString.h GRect.h GURL.h \
  Arrays.h GThreads.h debug.h
GOS.o: GOS.cpp ./config/config.h GException.h DjVuGlobal.h GThreads.h GOS.h \
  GString.h GContainer.h GSmartPointer.h GURL.h Arrays.h
GPixmap.o: GPixmap.cpp ./config/config.h GPixmap.h GSmartPointer.h DjVuGlobal.h \
  GString.h GContainer.h GException.h ByteStream.h Arrays.h GRect.h \
  GBitmap.h GThreads.h JPEGDecoder.h
GRect.o: GRect.cpp ./config/config.h GRect.h DjVuGlobal.h GException.h
GScaler.o: GScaler.cpp ./config/config.h GScaler.h GException.h DjVuGlobal.h \
  GRect.h GBitmap.h GSmartPointer.h GPixmap.h
GSmartPointer.o: GSmartPointer.cpp ./config/config.h GThreads.h DjVuGlobal.h \
  GException.h GSmartPointer.h
GString.o: GString.cpp ./config/config.h GString.h DjVuGlobal.h GContainer.h \
  GException.h GSmartPointer.h GThreads.h debug.h
GThreads.o: GThreads.cpp ./config/config.h GThreads.h DjVuGlobal.h GException.h \
  DjVuMessageLite.h GString.h GContainer.h GSmartPointer.h
GUnicode.o: GUnicode.cpp ./config/config.h GString.h DjVuGlobal.h GContainer.h \
  GException.h GSmartPointer.h
GURL.o: GURL.cpp ./config/config.h GException.h DjVuGlobal.h GOS.h GString.h \
  GContainer.h GSmartPointer.h GURL.h Arrays.h GThreads.h debug.h
IFFByteStream.o: IFFByteStream.cpp ./config/config.h IFFByteStream.h \
  DjVuGlobal.h GException.h GString.h GContainer.h GSmartPointer.h \
  ByteStream.h Arrays.h
IW44EncodeCodec.o: IW44EncodeCodec.cpp ./config/config.h IW44Image.h \
  GSmartPointer.h DjVuGlobal.h ZPCodec.h GContainer.h GException.h \
  GBitmap.h GPixmap.h IFFByteStream.h GString.h ByteStream.h Arrays.h \
  GRect.h MMX.h
IW44Image.o: IW44Image.cpp ./config/config.h IW44Image.h GSmartPointer.h \
  DjVuGlobal.h ZPCodec.h GContainer.h GException.h GBitmap.h GPixmap.h \
  IFFByteStream.h GString.h ByteStream.h Arrays.h GRect.h MMX.h
JB2EncodeCodec.o: JB2EncodeCodec.cpp ./config/config.h JB2Image.h GString.h \
  DjVuGlobal.h GContainer.h GException.h GSmartPointer.h ZPCodec.h \
  GBitmap.h
JB2Image.o: JB2Image.cpp ./config/config.h JB2Image.h GString.h DjVuGlobal.h \
  GContainer.h GException.h GSmartPointer.h ZPCodec.h GThreads.h GRect.h \
  GBitmap.h
JPEGDecoder.o: JPEGDecoder.cpp ./config/config.h JPEGDecoder.h GSmartPointer.h \
  DjVuGlobal.h ByteStream.h Arrays.h GException.h GPixmap.h
miniexp.o: miniexp.cpp ./config/config.h miniexp.h
MMRDecoder.o: MMRDecoder.cpp ./config/config.h MMRDecoder.h GSmartPointer.h \
  DjVuGlobal.h JB2Image.h GString.h GContainer.h GException.h ZPCodec.h \
  ByteStream.h Arrays.h GBitmap.h
MMX.o: MMX.cpp ./config/config.h MMX.h DjVuGlobal.h
UnicodeByteStream.o: UnicodeByteStream.cpp ./config/config.h \
  UnicodeByteStream.h DjVuGlobal.h GString.h GContainer.h GException.h \
  GSmartPointer.h ByteStream.h Arrays.h
XMLParser.o: XMLParser.cpp ./config/config.h XMLParser.h GContainer.h \
  GException.h DjVuGlobal.h GSmartPointer.h GURL.h GString.h Arrays.h \
  GThreads.h XMLTags.h ByteStream.h GOS.h DjVuDocument.h DjVuPort.h \
  DjVuText.h GMapAreas.h GRect.h DjVuAnno.h DjVuFile.h DjVuInfo.h \
  DjVuPalette.h GPixmap.h DjVuImage.h debug.h
XMLTags.o: XMLTags.cpp ./config/config.h XMLTags.h GContainer.h GException.h \
  DjVuGlobal.h GSmartPointer.h GString.h UnicodeByteStream.h ByteStream.h \
  Arrays.h
ZPCodec.o: ZPCodec.cpp ./config/config.h ZPCodec.h GContainer.h GException.h \
  DjVuGlobal.h GSmartPointer.h ByteStream.h Arrays.h
