#include "icon0_t_png.h"
#include "circle-outline_png.h"
#include "close-box-outline_png.h"
#include "triangle-outline_png.h"
#include "clock_png.h"
#include "battery-outline_png.h"
#include "memory_png.h"

#include "collections_bookmark_white-fs8_png.h"
#include "content_copy_white-fs8_png.h"
#include "search_white-fs8_png.h"
#include "rotate_left_white-fs8_png.h"
#include "rotate_right_white-fs8_png.h"

#include "bookmark_add_white-fs8_png.h"
#include "first_page-fs8_png.h"
#include "last_page-fs8_png.h"
#include "previous_ten-fs8_png.h"
#include "next_ten-fs8_png.h"
#include "go_to_page-fs8_png.h"

#include "fit_height-fs8_png.h"
#include "fit_width-fs8_png.h"
#include "zoom_out_white-fs8_png.h"
#include "zoom_in_white-fs8_png.h"